### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by owenfiscus** [elrumo/macOS-Big-Sur-icons-replacements#1]

**Comment by elrumo** [comment]
Just pushed a new commit with the icon for [Sublime.](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Sublime%20Text.icns)

[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Sublime%20Text.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Sublime%20Text.icns)
