### ISSUE TITLE
Icons appear transparent

### ISSUE THREAD

**Issue by timswagwalker** [elrumo/macOS-Big-Sur-icons-replacements#11]
When adding the icons onto the app in the Info pane, the icon doesn't show up at all, and a transparent icon is used. From what I've seen, this might require additional versions of the icons (@2x, etc.) to be exported into the .icns file

**Comment by isakdombestein** [comment]
I can confirm this issue. I've now changed the icons on Spotify and VS Code. Both apps are now transparent everywhere. Both in the dock, Application folder and in Spotlight. The icons doesn't react either when pressed in the Applications folder. 
I've attached some photos of this.

![Screenshot 2020-07-12 at 16 40 46](https://user-images.githubusercontent.com/13219213/87249302-ac01f200-c45e-11ea-9356-7af3cde47a2f.png)

![Screenshot 2020-07-12 at 16 41 17](https://user-images.githubusercontent.com/13219213/87249312-b7edb400-c45e-11ea-9f5b-e4d41806511f.png)

![Screenshot 2020-07-12 at 16 41 37](https://user-images.githubusercontent.com/13219213/87249323-c1771c00-c45e-11ea-8299-ad8dfb7435bb.png)

**Comment by elrumo** [comment]
I had that issue too, which seemed to be fixed, at least as a short term solution, by opening the file with preview, selecting all and copying the from there, and pasting it to the app info window. But I've found a more permanent solution, Big Sur seems to only let you drag and drop the icon if it's the right size, where as older versions seemed to use whatever was available. I'm re-exporting all the icons as a proper .icns wrapper with all the right sizes. I'll commit them later today. The screenshot bellow show how they should be now.

![image](https://user-images.githubusercontent.com/36299870/87250676-d6f04400-c466-11ea-9a58-fafdbc4f75d7.png)
