### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by AstralBirthVoid1** [elrumo/macOS-Big-Sur-icons-replacements#12]
Hey, could you make a Mac OS Big Sur icon for Minecraft?

Thanks!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Minecraft.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Minecraft.icns)<br>[Minecraft](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Minecraft.icns)

Done

**Comment by sn0wyfall** [comment]
@elrumo This Minecraft icon doesn't look right to me. Would it be possible not to add the outer shading? I feel like it takes away from Minecraft's design. Just the rounding would work in my humble opinion.

**Comment by AstralBirthVoid1** [comment]
Thank you so much!

**Comment by elrumo** [comment]
I've updated the icon so it now doesn't have the glossy effects.

**Comment by sn0wyfall** [comment]
@elrumo Thank you! It looks super good.
