### ISSUE TITLE
Final cut pro

### ISSUE THREAD

**Issue by imabhaysutar** [elrumo/macOS-Big-Sur-icons-replacements#14]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Final_Cut_Pro.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Final_Cut_Pro.icns)<br>[Final_Cut_Pro](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Final_Cut_Pro.icns)

Done :)
