### ISSUE TITLE
Logic Pro X

### ISSUE THREAD

**Issue by andresfelive** [elrumo/macOS-Big-Sur-icons-replacements#17]

**Comment by agraaaaao** [comment]
I've added the Logic Pro X icon into my google drive folder here: https://drive.google.com/drive/folders/135rutdxSqTACWjUhTPitYyKszysxCwQg?usp=sharing

**Comment by andresfelive** [comment]
thank you!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/png/Logic_Pro_X.png" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Logic_Pro_X.icns)<br>[Logic_Pro_X](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Logic_Pro_X.icns)  

Thanks for the icons!!
Just committed the new icons to the repo :)

P.s. The new icons are being uploaded (the .zip file with all the icons is 200mb+), so the link and image will appear broken until the upload is complete.
