### ISSUE TITLE
IINA

### ISSUE THREAD

**Issue by owenfiscus** [elrumo/macOS-Big-Sur-icons-replacements#2]
https://iina.io

Wanted to mention you did an incredible job with the Sublime Text icon, I'll keep posting suggestions if you want them but I appreciate your hard work!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Iina.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Iina.icns) [<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Iina_alt.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Iina_alt.icns)
Iina is actually my default media player, good shout.

Thanks!! And sure, not a problem at all. It's fun to work on small graphic design tasks during my free time.
