### ISSUE TITLE
Things 3

### ISSUE THREAD

**Issue by jojoapplemaniac** [elrumo/macOS-Big-Sur-icons-replacements#27]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Things_3.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Things_3.icns)<br>[Things 3](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Things_3.icns)  

This one has kindly been done by @agraaaaao

**Comment by jojoapplemaniac** [comment]
The link seems to return a 404 error

**Comment by elrumo** [comment]
Yes, just noticed my laptop went to sleep before the push command finished. Should be up shortly
