### ISSUE TITLE
Transmit

### ISSUE THREAD

**Issue by owenfiscus** [elrumo/macOS-Big-Sur-icons-replacements#3]
https://www.panic.com/transmit/

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Transmit.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Transmit.icns)
Transmit done  :)
