### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by Mashoe** [elrumo/macOS-Big-Sur-icons-replacements#5]
Inspiration: https://apps.apple.com/us/app/microsoft-onedrive/id477537958

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/OneDrive.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/OneDrive.icns)

Just finished the OneDrive icon, closing this issue.
