### ISSUE TITLE
Calibre - eBook management

### ISSUE THREAD

**Issue by tomasilheu** [elrumo/macOS-Big-Sur-icons-replacements#7]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Calibre.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Calibre.icns)<br>[Calibre](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Calibre.icns)

I'm not massively happy with this one, I think they're logo leaves a lot to be desired in the first place. But here it goes anyway.

**Comment by tomasilheu** [comment]
It looks great! Thank you very much, I love it!
